### ISSUE TITLE
Implementar Facade

### ISSUE THREAD

**Issue by vinnytxr** [eduardamaganino/padroes-de-projeto#2]
**Descrição da Issue:**
O objetivo desta tarefa é implementar o padrão de projeto Facade. O padrão Facade fornece uma interface simplificada para um conjunto de interfaces em um subsistema. Ele torna um subsistema mais fácil de usar ao fornecer uma interface de alto nível que facilita a interação com o sistema complexo subjacente.

**Requisitos:**
- Conceito do Padrão: Explique o que é o padrão Facade e como ele funciona.
- Problema que Resolve: Descreva os problemas que este padrão resolve e onde ele pode ser aplicado.
- Quando Usar o Padrão: Explicar os cenários em que o Facade é adequado.
- Diagrama UML: Inclua um diagrama UML que mostre a estrutura do Facade e como ele interage com os subsistemas.
- Exemplo de Código: Forneça um exemplo de código explicativo em uma linguagem escolhida pela equipe (exemplo: Java).
- Vantagens e Desvantagens: Apresente as principais vantagens e desvantagens deste padrão de projeto.

**Tarefas:**
- [x] Criar a implementação do padrão Facade em código.
- [x] Adicionar documentação clara e concisa sobre o padrão no repositório.
- [x] Criar um diagrama UML representando o padrão.

**Comment by eduardamaganino** [comment]
Eu quero essa issue
