### ISSUE TITLE
Implementar Template Method

### ISSUE THREAD

**Issue by eduardamaganino** [eduardamaganino/padroes-de-projeto#3]
**Descrição da Issue:**
O objetivo desta tarefa é implementar o padrão de projeto Template Method. O padrão define o esqueleto de um algoritmo em um método, deixando alguns passos a serem implementados pelas subclasses. Este padrão é útil quando você tem um algoritmo cujas partes podem ser variáveis, mas a estrutura geral permanece a mesma.

**Requisitos:**

- Conceito do Padrão: Explique o que é o padrão Template Method e como ele funciona.
- Problema que Resolve: Descreva os problemas que este padrão resolve e onde ele pode ser aplicado.
- Quando Usar o Padrão: Explicar os cenários em que o Template Method é adequado.
- Diagrama UML: Inclua um diagrama UML que mostre a estrutura do Template Method e como as subclasses interagem.
- Exemplo de Código: Forneça um exemplo de código explicativo em uma linguagem escolhida pela equipe (exemplo: Java).
- Vantagens e Desvantagens: Apresente as principais vantagens e desvantagens deste padrão de projeto.

**Tarefas:**

- [x] Criar a implementação do padrão Template Method em código.
- [x] Adicionar documentação clara e concisa sobre o padrão no repositório.
- [x] Criar um diagrama UML representando o padrão.

**Comment by vinnytxr** [comment]
vou querer implementar essa
