### ISSUE TITLE
Implementar Visitor

### ISSUE THREAD

**Issue by JMielli** [eduardamaganino/padroes-de-projeto#4]
*Descrição da Issue:*
O objetivo desta tarefa é implementar o padrão de projeto Visitor. O padrão Visitor permite que você adicione novas operações a objetos de uma estrutura sem mudar as classes dos objetos sobre os quais opera. Ele envolve a criação de um visitante que passa por uma coleção de objetos diferentes e executa alguma operação em cada um deles.

*Requisitos:*
- Conceito do Padrão: Explique o que é o padrão Visitor e como ele funciona.
- Problema que Resolve: Descreva os problemas que este padrão resolve e onde ele pode ser aplicado.
- Quando Usar o Padrão: Explicar os cenários em que o Visitor é adequado.
- Diagrama UML: Inclua um diagrama UML que mostre a estrutura do Visitor e como ele interage com os elementos.
- Exemplo de Código: Forneça um exemplo de código explicativo em uma linguagem escolhida pela equipe (exemplo: Java).
- Vantagens e Desvantagens: Apresente as principais vantagens e desvantagens deste padrão de projeto.

*Tarefas:*
- [x] Criar a implementação do padrão Visitor em código.
- [x] Adicionar documentação clara e concisa sobre o padrão no repositório.
- [x] Criar um diagrama UML representando o padrão.

**Comment by PabloSSena** [comment]
Quero fazer essa
