### ISSUE TITLE
Implementar Strategy

### ISSUE THREAD

**Issue by PabloSSena** [eduardamaganino/padroes-de-projeto#5]
**Descrição da Issue:**
O objetivo desta tarefa é implementar o padrão de projeto Strategy. O padrão Strategy permite que você defina uma família de algoritmos, coloque cada um deles em uma classe separada e torne os seus objetos intercambiáveis. Este padrão permite que o algoritmo varie independentemente dos clientes que o utilizam.

**Requisitos:**
- Conceito do Padrão: Explique o que é o padrão Strategy e como ele funciona.
- Problema que Resolve: Descreva os problemas que este padrão resolve e onde ele pode ser aplicado.
- Quando Usar o Padrão: Explicar os cenários em que o Strategy é adequado.
- Diagrama UML: Inclua um diagrama UML que mostre a estrutura do Strategy e como as subclasses interagem.
- Exemplo de Código: Forneça um exemplo de código explicativo em uma linguagem escolhida pela equipe (exemplo: Java).
- Vantagens e Desvantagens: Apresente as principais vantagens e desvantagens deste padrão de projeto.

**Tarefas:**
- [ ] Criar a implementação do padrão Strategy em código.
- [ ] Adicionar documentação clara e concisa sobre o padrão no repositório.
- [ ] Criar um diagrama UML representando o padrão.

**Comment by JMielli** [comment]
Eu quero essa issue

**Comment by JotaveX** [comment]
Quero fazer essa
