### ISSUE TITLE
Implementar Proxy

### ISSUE THREAD

**Issue by JotaveX** [eduardamaganino/padroes-de-projeto#6]
*Descrição da Issue:*
O objetivo desta tarefa é implementar o padrão de projeto Proxy. O padrão Proxy fornece um substituto ou marcador para outro objeto para controlar o acesso a ele. Este padrão pode ser utilizado para prover um acesso controlado, carregar objetos de forma preguiçosa, ou mesmo para adicionar uma camada de segurança.

*Requisitos:*
- Conceito do Padrão: Explique o que é o padrão Proxy e como ele funciona.
- Problema que Resolve: Descreva os problemas que este padrão resolve e onde ele pode ser aplicado.
- Quando Usar o Padrão: Explicar os cenários em que o Proxy é adequado.
- Diagrama UML: Inclua um diagrama UML que mostre a estrutura do Proxy e como ele interage com os objetos reais.
- Exemplo de Código: Forneça um exemplo de código explicativo em uma linguagem escolhida pela equipe (exemplo: Java).
- Vantagens e Desvantagens: Apresente as principais vantagens e desvantagens deste padrão de projeto.

*Tarefas:*
- [x] Criar a implementação do padrão Proxy em código.
- [x] Adicionar documentação clara e concisa sobre o padrão no repositório.
- [x] Criar um diagrama UML representando o padrão.

**Comment by JMielli** [comment]
Quero essa issue
